---
- name: Prepare
  hosts: all
  vars:
    docker_apt_signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    docker_apt_uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    docker_architecture_map:
      "x86_64": "amd64"
      "aarch64": "arm64"
      "aarch": "arm64"
      "armhf": "armhf"
      "armv7l": "armhf"

    docker_dependencies:
      - apt-transport-https
      - gnupg2
      - python3-debian
      - python3-docker
    docker_packages:
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-ce-rootless-extras
      - docker-compose-plugin
    git_packages:
      - git
    docker_package_state: present

  tasks:
    - name: Install Docker dependencies
      ansible.builtin.apt:
        name: "{{ docker_dependencies }}"
        update_cache: true

    - name: Configure Docker APT repository
      ansible.builtin.deb822_repository:
        architectures: "{{ docker_architecture_map[ansible_architecture] }}"
        components: stable
        name: docker
        signed_by: "{{ docker_apt_signed_by }}"
        suites: "{{ ansible_distribution_release }}"
        uris: "{{ docker_apt_uris }}"

    - name: Install required packages
      ansible.builtin.apt:
        name: "{{ docker_packages + git_packages }}"
        state: present
        update_cache: true

    - name: Ensure Docker daemon is running
      ansible.builtin.service:
        name: docker
        state: started
